# Generated by Django 5.1.4 on 2024-12-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
